# Can be used as a calculator, like MATLAB

In [ ]:
A = rand(4, 4)

In [4]:
B = 2 .* ones(4, 4)
C = A .* B

4×4 Matrix{Float64}:
 0.510303  1.29694   1.77454    0.327535
 1.51629   0.460503  0.0230757  0.412156
 1.75127   0.713547  1.97416    0.51041
 0.876847  1.20551   1.62937    1.98022

In [6]:
A[1, 1] = 0
A

4×4 Matrix{Float64}:
 0.0       0.648472  0.887271   0.163767
 0.758145  0.230252  0.0115379  0.206078
 0.875635  0.356773  0.987082   0.255205
 0.438424  0.602754  0.814685   0.990112

In [8]:
D = A
D[2, 2] = 1
A # D and A are the same

4×4 Matrix{Float64}:
 0.0       0.648472  0.887271   0.163767
 0.758145  1.0       0.0115379  0.206078
 0.875635  0.356773  0.987082   0.255205
 0.438424  0.602754  0.814685   0.990112

# Packages and package management

In [10]:
using Statistics
mean(A)

0.562246252295428

In [12]:
using Pkg # the package manager
Pkg.add("Oceananigans")

   Resolving package versions...
  No Changes to `~/Projects/SaltySnacks.jl/Project.toml`
  No Changes to `~/Projects/SaltySnacks.jl/Manifest.toml`


In [13]:
using Oceananigans

# Types, constructors, functions, keyword arguments